In [1]:
from rec_gov_automate import FourRivers

In [6]:
river = FourRivers.get_main_salmon()

river

FourRivers (234622)

In [7]:
avail_df = river.get_permit_season_availability()

avail_df

,river,date,total,remaining,retrive_timestamp,days_to_launch
0,main_salmon,2025-05-28 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,105
1,main_salmon,2025-05-29 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,106
2,main_salmon,2025-05-30 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,107
3,main_salmon,2025-05-31 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,108
4,main_salmon,2025-06-01 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,109
...,...,...,...,...,...,...
94,main_salmon,2025-08-30 00:00:00+00:00,8,0,2025-02-11 19:02:34.537575+00:00,199
95,main_salmon,2025-08-31 00:00:00+00:00,8,0,2025-02-11 19:02:34.537575+00:00,200
96,main_salmon,2025-09-01 00:00:00+00:00,8,0,2025-02-11 19:02:34.537575+00:00,201
97,main_salmon,2025-09-02 00:00:00+00:00,8,0,2025-02-11 19:02:34.537575+00:00,202
98,main_salmon,2025-09-03 00:00:00+00:00,8,0,2025-02-11 19:02:34.537575+00:00,203

In [10]:
avail_df[avail_df['remaining'] > 0]

,river,date,total,remaining,retrive_timestamp,days_to_launch
0,main_salmon,2025-05-28 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,105
1,main_salmon,2025-05-29 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,106
2,main_salmon,2025-05-30 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,107
3,main_salmon,2025-05-31 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,108
4,main_salmon,2025-06-01 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,109
5,main_salmon,2025-06-02 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,110
6,main_salmon,2025-06-03 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,111
7,main_salmon,2025-06-04 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,112
8,main_salmon,2025-06-05 00:00:00+00:00,99,98,2025-02-11 19:02:34.537575+00:00,113
9,main_salmon,2025-06-06 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,114
10,main_salmon,2025-06-07 00:00:00+00:00,99,97,2025-02-11 19:02:34.537575+00:00,115
11,main_salmon,2025-06-08 00:00:00+00:00,99,98,2025-02-11 19:02:34.537575+00:00,116
12,main_salmon,2025-06-09 00:00:00+00:00,99,96,2025-02-11 19:02:34.537575+00:00,117
13,main_salmon,2025-06-10 00:00:00+00:00,99,99,2025-02-11 19:02:34.537575+00:00,118
14,main_salmon,2025-06-11 00:00:00+00:00,99,97,2025-02-11 19:02:34.537575+00:00,119
15,main_salmon,2025-06-12 00:00:00+00:00,99,96,2025-02-11 19:02:34.537575+00:00,120
16,main_salmon,2025-06-13 00:00:00+00:00,99,96,2025-02-11 19:02:34.537575+00:00,121
17,main_salmon,2025-06-14 00:00:00+00:00,99,97,2025-02-11 19:02:34.537575+00:00,122
18,main_salmon,2025-06-15 00:00:00+00:00,99,92,2025-02-11 19:02:34.537575+00:00,123
19,main_salmon,2025-06-16 00:00:00+00:00,99,95,2025-02-11 19:02:34.537575+00:00,124
20,main_salmon,2025-06-17 00:00:00+00:00,99,96,2025-02-11 19:02:34.537575+00:00,125
21,main_salmon,2025-06-18 00:00:00+00:00,99,94,2025-02-11 19:02:34.537575+00:00,126
22,main_salmon,2025-06-19 00:00:00+00:00,99,76,2025-02-11 19:02:34.537575+00:00,127

In [11]:
river.check_availability(day=28, month=5)

True